# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/isort
    rev: v5.13.2
    hooks:
    -   id: isort
        name: isort
        entry: isort --tc --lines-after-imports=2 ./code
        language: system
        types: [ python ]
        pass_filenames: false

-   repo: https://github.com/psf/black
    rev: v24.10.0
    hooks:
    -   id: black
        name: black
        entry: black --line-length=79 ./code
        language: system
        types: [ python ]
        pass_filenames: false

-   repo: https://github.com/PyCQA/flake8
    rev: v7.1.1
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 ./code
        language: system
        types: [ python ]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "sh mypy_run.sh"
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true